#!/bin/bash
alias b='npm run-script build'
alias cde='cd /c/Users/oswaldo.plazola/eclipse-workspace'
alias cdh='cd /c/hygieia-latest/hygieia/hygieia/'
alias cdldap='cd /c/Users/oswaldo.plazola/Documents/OCC/ldap-mock/'
alias cdown='cd /c/Users/oswaldo.plazola/Downloads/'
alias cdp='cd /c/"Program Files"/'
alias cdst='cd ~/shell/mvntest/SeleniumTest/src/main/java/com/selenium/seltest'
alias cdw='cd /c/Users/oswaldo.plazola/Documents/OCC/ldap-mock'
alias cdxampp='cd /c/xampp/htdocs/'
alias chmod644='find . -type f -exec chmod 644 {} +'
alias chmod755='find . -type d -exec chmod 755 {} +'
alias d='docker'
alias denv='eval $(docker-machine env default)'
alias devices='adb devices'
alias di='docker images'
alias dt='echo `date +"%m/%d/%Y %H:%M"`'
alias g='git'
alias grep3='grep -A 3 -B 3 -rn '
alias gt='git status'
alias h='history'
alias k='kubectl'
alias l='ls -CF'
alias ll='ls -laF'
alias ls='ls -F --color=auto --show-control-chars'
alias node='winpty node.exe'
alias pindex='cp public/index.html /c/xampp/htdocs/index.html'
alias push='cp -a public/. /c/xampp/htdocs/;echo `date +"%m/%d/%Y %H:%M"`'
alias vi=vim

