apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: ${NAMESPACE}
  labels:
    service: ${SERVICE_NAME}
  name: ${SERVICE_NAME}
spec:
  ports:
  - name: "api"
    port: 7305
    protocol: TCP
    targetPort: 7305
  selector:
    service: ${SERVICE_NAME}
  sessionAffinity: None
  type: ClusterIP
